name:                uno-server
version:             0.1.0.0
github:              "githubuser/uno-server"
license:             BSD3
author:              "Ugo Bourdon"
maintainer:          "bourdon.ugo@gmail.com"
copyright:           "2018 Ugo Bourdon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/uno-server#readme>

dependencies:
- base >= 4.7 && < 5
# utils
- uuid >= 1.3.13
- text

library:
  source-dirs: src

executables:
  uno-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uno-server

tests:
  uno-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uno-server
    - hspec
    - hspec-discover
